### ISSUE TITLE
Auto-detect the model?

### ISSUE THREAD

**Issue by StevenLooman** [mzdrale/pyubee#4]
Is there a way to auto-detect the model? Perhaps there is a default URL which will always give something from which the model can be read, or there is a URL unique for each model which can be checked?

**Comment by mzdrale** [comment]
I was thinking about that, but then I realized there are [many Ubee models](http://www.ubeeinteractive.com/products/cable) there and I'm not sure is there easy way to detect the model. We have access to 2 different models, your `EVW3200-Wifi` and my `EVW32C-0N` and I'm not sure if it's enough to find a good way to detect model. 
We can try. 🙂

**Comment by mzdrale** [comment]
@StevenLooman do you have /UbeeSysInfo.asp URL on your router? I have it on `EVW32C-0N` and it shows model beside other information about router.

<img width="616" alt="Screen Shot 2019-03-23 at 23 01 30" src="https://user-images.githubusercontent.com/6348596/54872139-ee15a900-4dbf-11e9-85c7-5d41558030e9.png">

**Comment by StevenLooman** [comment]
No, unfortunately not.

I have these, ISP-specific marked, per menu-item:
```
/			(ISP)
/RgHomeMR3.asp		(ISP)

Basic
/BasicCmState.asp
/BasicFirmware.asp
/BasicStatus.asp
/BasicSecurity.asp
/BasicFactoryDefault.asp

Telephony
/AdvMta.asp
/AdvLine.asp

Gateway
/RgSetup.asp
/RgDhcp.asp
/RgDdns.asp
/RgBackup.asp
/RgTime.asp
/RgOptions.asp
/RgStaticLease.asp
/RgIpFiltering.asp
/RgMacFiltering.asp
/RgPortFiltering.asp
/RgForwarding.asp
/RgPortTriggering.asp
/RgDmzHost.asp

Firewall
/RgContentFilter.asp
/RgFirewallEL.asp
/RgFirewallRL.asp

Parental Control
/RgUserSetup.asp
/RgParentalBasic.asp
/RgTodFilter.asp
/RgParentalEL.asp

VPN
/RgVpnBasic.asp
/RgVpnConfigure.asp
/RgVpnEventLog.asp

Wireless
/wlanRadio.asp
/wlanPrimaryNetwork.asp
/wlanAdvanced.asp
/wlanAccess.asp
/wlanWmm.asp
/wlanBridging.asp

Wifispots		(ISP)
/wlanHomeHotspot.asp

Logout
/logout.asp
```

The only page containing identifying information about the type is `BasicFirmware.asp`, which shows the cable modem serial number.

**Comment by StevenLooman** [comment]
When I do a UPnP search the device responds with an the URL `/RootDevice.xml`. This contains more information about the device:
```


<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
   <specVersion>
      <major>1</major>
      <minor>0</minor>
   </specVersion>
   <URLBase>http://192.168.178.1:80</URLBase>
   <device>
      <deviceType>urn:schemas-upnp-org:device:InternetGatewayDevice:1</deviceType>
      <friendlyName>Ambit EVW320B</friendlyName>
      <manufacturer>Ambit</manufacturer>
      <manufacturerURL>http://www.ubeeinteractive.com</manufacturerURL>
      <modelDescription>EVW320B</modelDescription>
      <modelName>EVW320B</modelName>
      <modelNumber>EVW320B</modelNumber>
      <modelURL>http://www.ubeeinteractive.com</modelURL>
      <serialNumber>(unimplemented)</serialNumber>
      <UDN>uuid:upnp-InternetGatewayDevice-1_0-889ffacb9043</UDN>
      <UPC>(unimplemented)</UPC>
      <serviceList>
         <service>
            <serviceType>urn:schemas-upnp-org:service:Layer3Forwarding:1</serviceType>
            <serviceId>urn:upnp-org:serviceId:L3Forwarding1</serviceId>
            <SCPDURL>/Layer3Forwarding.xml</SCPDURL>
            <controlURL>/Layer3Forwarding</controlURL>
            <eventSubURL>/Layer3Forwarding</eventSubURL>
         </service>
      </serviceList>
      <deviceList>
         <device>
            <deviceType>urn:schemas-upnp-org:device:WANDevice:1</deviceType>
            <friendlyName>Ambit EVW320B</friendlyName>
            <manufacturer>Ambit</manufacturer>
            <manufacturerURL>http://www.ubeeinteractive.com</manufacturerURL>
            <modelDescription>EVW320B</modelDescription>
            <modelName>EVW320B</modelName>
            <modelNumber>EVW320B</modelNumber>
            <modelURL>http://www.ubeeinteractive.com</modelURL>
            <serialNumber>(unimplemented)</serialNumber>
            <UDN>uuid:upnp-WANDevice-1_0-889ffacb9043</UDN>
            <UPC>(unimplemented)</UPC>
            <serviceList>
               <service>
                  <serviceType>urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1</serviceType>
                  <serviceId>urn:upnp-org:serviceId:WANCommonIFC1</serviceId>
                  <SCPDURL>/WANCommonInterfaceConfig.xml</SCPDURL>
                  <controlURL>/WANCommonInterfaceConfig</controlURL>
                  <eventSubURL>/WANCommonInterfaceConfig</eventSubURL>
               </service>
            </serviceList>
            <deviceList>
               <device>
                  <deviceType>urn:schemas-upnp-org:device:WANConnectionDevice:1</deviceType>
                  <friendlyName>Ambit EVW320B</friendlyName>
                  <manufacturer>Ambit</manufacturer>
                  <manufacturerURL>http://www.ubeeinteractive.com</manufacturerURL>
                  <modelDescription>EVW320B</modelDescription>
                  <modelName>EVW320B</modelName>
                  <modelNumber>EVW320B</modelNumber>
                  <modelURL>http://www.ubeeinteractive.com</modelURL>
                  <serialNumber>(unimplemented)</serialNumber>
                  <UDN>uuid:upnp-WANConnectionDevice-1_0-889ffacb9043</UDN>
                  <UPC>(unimplemented)</UPC>
                  <serviceList>
                     <service>
                        <serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType>
                        <serviceId>urn:upnp-org:serviceId:WANIPConn1</serviceId>
                        <SCPDURL>/WANIPConnection.xml</SCPDURL>
                        <controlURL>/WANIPConnection</controlURL>
                        <eventSubURL>/WANIPConnection</eventSubURL>
                     </service>
                  </serviceList>
               </device>
            </deviceList>
         </device>
      </deviceList>
      <presentationURL>/</presentationURL>
   </device>
</root>


```

**Comment by mzdrale** [comment]
I have `/RootDevice.xml`, too and it shows my model `EVW32C-0N`, so I guess we can use this to detect model.
I updated code to autodetect model, tested locally and it's working for me. Later today I will upload, so you can test if you have time.
BTW, your model is shown as `EVW320B` here, not `EVW3200-Wifi` as you reported earlier?

**Comment by StevenLooman** [comment]
Will do later today.

**Comment by mzdrale** [comment]
You can install `pyubee-0.4.dev1`:

```
python3 -m pip install pyubee==0.4.dev1
```

Updated version of Home Assistant Ubee Device Tracker is [here](https://gitlab.com/mzdrale/hass-ubee-device-tracker/blob/master/ubee.py).

**Comment by StevenLooman** [comment]
> BTW, your model is shown as `EVW320B` here, not `EVW3200-Wifi` as you reported earlier?

You are right. The modem seems to have two 'names':
- Ambit EVW320B
- Ubee EVW3200-Wifi

Perhaps my ISP (Ziggo in The Netherlands, Liberty Global globally) has changed the brand/part numbers? This is what is on the modem itself:
![IMG_20190326_200225_edit](https://user-images.githubusercontent.com/724259/55027054-a338a300-5004-11e9-8058-c908c88671a1.jpg)

If you google for `Ubee EVW3200 Wifi` you'll also find several pages using this name, mostly related (at least in the search results I'm getting) to Ziggo.

Perhaps we should create an alias, such that users have less hassle when manually providing the model.

**Comment by mzdrale** [comment]
I was thinking about that earlier. I guess there are different models with same URLs like

```
        'url_session_active': '/BasicStatus.asp',
        'url_login': '/goform/loginMR3',
        'url_logout': '/logout.asp',
        'url_connected_devices_lan': '/RgDhcp.asp',
        'url_connected_devices_wifi': '/wlanAccess.asp',
```

so I planned to go with something like 

```
    'model1': {
        'url_session_active': '/BasicStatus.asp',
        'url_login': '/goform/loginMR3',
        'url_logout': '/logout.asp',
        'url_connected_devices_lan': '/RgDhcp.asp',
        'url_connected_devices_wifi': '/wlanAccess.asp',
        'regex_login': re.compile(r'<title>Residential Gateway Login</title>'),
        'regex_wifi_devices': re.compile(
            r'<tr bgcolor=#[0-9a-fA-F]+>'
            r'<td>([0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:' # mac address
            r'[0-9a-fA-F]{2}:[0-9a-fA-F]{2})</td>'  # mac address, cont'd
            r'<td>\d+</td>'  # age
            r'<td>.+</td>'  # rssi
            r'<td>.*</td>'  # ip address
            r'<td>(.+)?</td>'  # hostname
            r'<td>.+</td>'  # mode
            r'<td>\d+</td>'  # speed
            r'</tr>'
        ),
        'regex_lan_devices': re.compile(
            r'<tr bgcolor=#[0-9a-fA-F]+>'
            r'<td>([0-9a-fA-F]{12})</td>'  # mac address
            r'<td>(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})</td>'  # ip address
        ),
    },
    'model2': {
       ....
    },
    'model3': {
       ....
    },
    ...
```

and then do mapping, for example:

```
EVW32C-0N ---> model1
EVW320B ---> model2
EVW3200-Wifi ---> model2
...
```

Does that sound good to you?
I'm going to create new issue for this.

BTW, I released `pyubee 0.4.dev2` with `EVW3200-Wifi` renamed to `EVW320B`, so if you install this version, autodetection should work for you. Could you test it please? Don't forget to update [HASS Ubee Device Tracker](https://gitlab.com/mzdrale/hass-ubee-device-tracker/blob/master/ubee.py) and remove `model` from `configuration.yaml`.

**Comment by StevenLooman** [comment]
> Does that sound good to you?

It's a trade-off. On the one hand you create flexibility. On the other hand you introduce indirectionality (is that a word?) and complexity. Also, why is `model1` called `model1`? This would be something I'd ask myself if I would see this code in three months.

This is also an option:
```python
aliases = {
    'EVW3200-Wifi': 'EVW320B',
}

if model in aliases:
    model = aliases[model]

model_info = MODELS[model]
```

Your call. I prefer the latter but that is mostly personal.

**Comment by StevenLooman** [comment]
Also, there is no need to push development-versions to pypi. I can just pull this repository and test from there.

**Comment by mzdrale** [comment]
It was just suggestion and I wasn’t sure it’s the best way to do. That’s why asked for your opinion and thanks for quick answer.
The reason I suggested model1, model2, ..., modelN is because I think there are different models with the same parameters we need (wifi connected devices url, lan connected devices url ...). So for example you have model `EVW320B` and model `EVW330C` (just guessing model names), which are completely different models, but they have the same URLs. In that case you can’t say `EVW330C` is an alias for `EVW320B`, but you can use the same entry for both of them.
I said I’m going to open separate issue for this alias stuff and I didn’t do that, sorry. :)

Can we close this “model auto-detect” issue first, so we can use version with model auto-detect in next Home Assistant version? When you get a chance to test `0.4.dev2`, could you do it? Suggest any changes you think we can make, of course.

**Comment by StevenLooman** [comment]
> I said I’m going to open separate issue for this alias stuff and I didn’t do that, sorry. :)

No need to be sorry. My feedback was by no means with the intention to berate you, only to help.

I have added `tox` support to `pyubee`. If you run `tox` from the `pyubee`-directory it will run `flake8`, `pylint`, and `pydocstyle` to check for (style) errors.

The auto-detect works for me. Great work building this!

**Comment by StevenLooman** [comment]
To install tox run this:
```
$ pip install tox
```

Then to run it:
```
$ tox
```

**Comment by mzdrale** [comment]
>
> No need to be sorry. My feedback was by no means with the intention to berate you, only to help.
> 

Don't worry, I understand it's help. 🙂 

> I have added `tox` support to `pyubee`. If you run `tox` from the `pyubee`-directory it will run `flake8`, `pylint`, and `pydocstyle` to check for (style) errors.
> 

Thanks.

> The auto-detect works for me. Great work building this!

Thank you for help and testing.
