### ISSUE TITLE
Not working Ubee EVW321B  (Ziggo NL)

### ISSUE THREAD

**Issue by Haggard** [mzdrale/pyubee#9]
Ubee EVW321B is not working with device_tracker

Traceback (most recent call last):
```
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/device_tracker/__init__.py", line 170, in async_setup_platform
    platform.get_scanner, hass, {DOMAIN: p_config})
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/ubee/device_tracker.py", line 34, in get_scanner
    ubee = Ubee(host, username, password, model)
  File "/usr/local/lib/python3.7/site-packages/pyubee/__init__.py", line 91, in __init__
    raise LookupError('Unknown model')
LookupError: Unknown model
```

**Comment by StevenLooman** [comment]
Thank you for the issue. I'm hoping your model is mostly compatible with the EVW320B.

Some things you can test:
- Does it have this url? http://192.168.1.1/RootDevice.xml (might have to change the IP to the one of your router)? Can you provide the file if so?
- Do the URLs found at https://github.com/mzdrale/pyubee/blob/master/pyubee/__init__.py#L128 work for your model?

**Comment by karrukola** [comment]
Hello @StevenLooman,
I too have that device at home and I think I managed to add the support for it; I have just raised the PR with my code.

I am not sure which evidence I have to provide. Please advise.

Also see attached [RootDevice.txt](https://github.com/mzdrale/pyubee/files/3270869/RootDevice.txt)

**Comment by StevenLooman** [comment]
Great work! v0.7 has been released already (courtesy @mzdrale). If you want integration into home assistant you'll have to create a PR there, upgrading the used version of the library, using [this file](https://github.com/home-assistant/home-assistant/blob/24766df1791c5cabe6e53d4a4a4d9c2dd7f31601/homeassistant/components/ubee/manifest.json).

**Comment by mzdrale** [comment]
Hey, I already created Home Assistant PR: [#24477](https://github.com/home-assistant/home-assistant/pull/24477).

**Comment by mzdrale** [comment]
Thank you guys!
I'm going to close this issue, since pyubee is working with EVW321B model now.
